// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAccount = "a_account"

// Account mapped from table <a_account>
type Account struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // ID
	Username  string    `gorm:"column:username;not null" json:"username"`
	Pwd       string    `gorm:"column:pwd;not null" json:"pwd"`
	Email     string    `gorm:"column:email;not null" json:"email"`
	Phone     string    `gorm:"column:phone;not null" json:"phone"`
	State     int32     `gorm:"column:state;not null;default:0" json:"state"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	Roles     []Role    `gorm:"many2many:user2role;" json:"roles"`
}

// TableName Account's table name
func (*Account) TableName() string {
	return TableNameAccount
}
