// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRole = "a_role"

// Role mapped from table <a_role>
type Role struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 角色ID
	PID       int32          `gorm:"column:p_id;not null;default:0" json:"p_id"`
	Nodes     string         `gorm:"column:nodes;not null" json:"nodes"`
	Name      string         `gorm:"column:name;not null" json:"name"`
	Desc      string         `gorm:"column:desc;not null" json:"desc"`
	OperateID int32          `gorm:"column:operate_id;not null;default:0" json:"operate_id"`
	CreatedAt time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
