// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRule = "a_rule"

// Rule mapped from table <a_rule>
type Rule struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Domain    string         `gorm:"column:domain;not null" json:"domain"`         // 域
	Name      string         `gorm:"column:name;not null" json:"name"`             // 规则名称
	Remark    string         `gorm:"column:remark;not null" json:"remark"`         // 描述
	CreatedAt time.Time      `gorm:"column:created_at;not null" json:"created_at"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;not null" json:"updated_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`          // 删除时间
}

// TableName Rule's table name
func (*Rule) TableName() string {
	return TableNameRule
}
