http:
 name: ghub
 Port: 8080
 timeout: 5s
 openApi: true

log:
 filename: ../../runtimes/logs/worker.log
 maxSize: 500
 maxBackups: 3
 maxAge: 3
 level: "debug"
 stdout: true

db:
 host: 39.100.139.50
 port: 30008
 database: enbrands
 user: prod
 pwd: g*bb5fo2eFKZb7clgoCy6Tpmd*#m39
 prefix: t_
redis:
 addr: 39.100.150.21:30005
 password: YJF#33bbe31d51b3b60370dc5%2016
 db: 1